### ISSUE TITLE
wrong version in the file header

### ISSUE THREAD

**Issue by master-lincoln** [SlexAxton/Jed#30]
The file contains an obsolete version number (0.5beta) in the top comment:
https://github.com/SlexAxton/Jed/blob/master/jed.js#L2

This should either be removed or kept up to date to prevent confusion.

**Comment by olizilla** [comment]
Looks like this is fixed now.

**Comment by olizilla** [comment]
Fixed in https://github.com/SlexAxton/Jed/commit/a19904289713baf45151466e9a8b176acd7a0e7c
