### ISSUE TITLE
po2json for new Jed format

### ISSUE THREAD

**Issue by mikeedwards** [SlexAxton/Jed#36]
Hey Jed folks! A couple of us were having a discussion about the new Jed format downstream at mikeedwards/po2json#32 . We're trying to figure out what the best output for something like this:

```
msgid "one product"
msgid_plural "%d products"
msgstr[0] "jeden produkt"
msgstr[1] "%d produkty"
msgstr[2] "%d produktów"
```

We were outputting (correctly or not):
```json
         "one product": [
            "%d products",
            "jeden produkt",
            "%d produkty",
            "%d produktów"
         ],
```

Would it be like this now that the zeroth element is being lopped off?
```json
         "one product": [
            "jeden produkt"
         ],
         "%d products": [
            "jeden produkt",
            "%d produkty",
            "%d produktów"
         ]
```

**Comment by mikeedwards** [comment]
Hey all. I just released po2json 0.4.1, and I've removed that first element so that it conforms to Jed as it now stands. Should I close this issue? Or do you think there might be revisions to the Jed format?

**Comment by JSteunou** [comment]
Hi @mikeedwards 

saw that yesterday, going to do a lot of tests with Jed 1.1 today & tomorrow, I'll keep you posted if I notice something wrong.

**Comment by JSteunou** [comment]
@mikeedwards for what I could test, this seems fine to me. I dont have specifics domain nor context, so I cant tell for this part, but plurals are fixed.

**Comment by mikeedwards** [comment]
Great, thanks for testing!
